services:
  glance:
    container_name: glance
    image: nginx:1.27-alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Vienna
    ports:
      - "192.168.54.111:8082:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - glance_default

networks:
  glance_default:
    name: glance_default
    ipam:
      config:
        - subnet: 192.168.250.0/24
          gateway: 192.168.250.1
