services:
  kandev:
    image: kandev:custom
    container_name: kandev
    restart: unless-stopped
    hostname: 'kandev-1.docker-1-pve-104-1140b-vie-at-magenta.rwnix.net'
    ports:
      - '192.168.54.111:38429:38429'
    volumes:
      - ./data:/data
    environment:
      - PATH=/data/home/.opencode/bin:/data/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - KANDEV_GITLAB_HOST=http://192.168.54.111:8080
    shm_size: '256m'
