{
 "title": "Power by Circle",
 "tags": [
  "smart-home",
  "tasmota"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "P04 — Sum of power (W)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P04\"})"
    }
   ]
  },
  {
   "title": "P04 — Power (W) over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P04\"})",
     "legendFormat": "P04"
    }
   ]
  },
  {
   "title": "P05 — Sum of power (W)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P05\"})"
    }
   ]
  },
  {
   "title": "P05 — Power (W) over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P05\"})",
     "legendFormat": "P05"
    }
   ]
  },
  {
   "title": "P06 — Sum of power (W)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P06\"})"
    }
   ]
  },
  {
   "title": "P06 — Power (W) over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P06\"})",
     "legendFormat": "P06"
    }
   ]
  },
  {
   "title": "P07 — Sum of power (W)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P07\"})"
    }
   ]
  },
  {
   "title": "P07 — Power (W) over time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "targets": [
    {
     "expr": "sum(tasmota_energy_Power{circle=\"P07\"})",
     "legendFormat": "P07"
    }
   ]
  }
 ]
}