services:
  kandev:
    image: kandev:custom
    container_name: kandev-2
    restart: unless-stopped
    command: ["kandev", "start", "--backend-port", "38430", "--verbose"]
    hostname: "kandev-2.docker-1-pve-104-1140b-vie-at-magenta.rwnix.net"
    ports:
      - "192.168.54.111:38430:38430"
      - "192.168.54.111:22022:22"
    volumes:
      - ./data:/data
    environment:
      - PATH=/data/home/.opencode/bin:/data/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - KANDEV_GITLAB_HOST=http://192.168.54.111:8080
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
    mem_limit: 3g
    cpus: 10
    shm_size: "256m"

networks:
  default:
    name: kandev2_default
    driver: bridge
    ipam:
      config:
        - subnet: 10.74.0.0/16
